/home/d10x_customer/bridgestone/repo/d10xipr/python/packages/dxdj/dxdj/dxcore/common_settings.py:756: UserWarning: Settings Warning : Default AutoField is set to BigAutoField. For backward
                compatibility you may have override it set to django.db.models.AutoField
  warnings.warn(msg, stacklevel=0)
Traceback (most recent call last):
  File "manage.py", line 26, in <module>
    main()
  File "manage.py", line 22, in main
    execute_from_command_line(sys.argv)
  File "/home/d10x_customer/bridgestone/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/d10x_customer/bridgestone/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/d10x_customer/bridgestone/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/d10x_customer/bridgestone/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/d10x_customer/bridgestone/venv/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/d10x_customer/bridgestone/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 92, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/d10x_customer/bridgestone/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/d10x_customer/bridgestone/venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/home/d10x_customer/bridgestone/venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 259, in build_graph
    self.graph.validate_consistency()
  File "/home/d10x_customer/bridgestone/venv/lib/python3.8/site-packages/django/db/migrations/graph.py", line 195, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/home/d10x_customer/bridgestone/venv/lib/python3.8/site-packages/django/db/migrations/graph.py", line 195, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/home/d10x_customer/bridgestone/venv/lib/python3.8/site-packages/django/db/migrations/graph.py", line 58, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration iam.0001_initial dependencies reference nonexistent parent node ('auth', '0012_alter_user_first_name_max_length')
